preprocessing:
  n_frames_to_skip: 4
  n_frames_per_state: 4
  patch_size: 84
  grayscale: true
  noop_max: 30
  scale_obs: false
  episode_life: true
  clip_rewards: true
  fire_reset: false
buffer_capacity: 1000000
num_initial_replay_samples: 100 # 50000
num_episodes: 2000
batch_size: 32
eps_max: 1
eps_min: 0.1
eps_decay_steps: 1000000
gamma: 0.99  # discount factor
c: 10000  # num steps after which to do target update
save_video_every: 100
checkpoint_every: 250
home_directory: /Users/pierclgr/PycharmProjects/AAS_project/
env_name: BreakoutNoFrameskip-v4
game: Breakout
checkpoint_file: breakout_checkpoint
video_file: breakout
model: DQNNetwork
output_model_file: breakout_final_model
max_steps_per_episode: 10000
logging: false # true
in_colab: true
reproducibility:
  train_seed: 1507
  test_seed: 2307
optimizer:
  lr: 0.00025
  momentum: 0.95
  squared_momentum: 0.95
  min_squared_gradient: 0.01