preprocessing:
  n_frames_to_skip: 4
  n_frames_per_state: 4
  patch_size: 84
  grayscale: true
buffer_capacity: 10000
num_episodes: 10
batch_size: 32
eps_max: 1
eps_min: 0.01
eps_decay_steps: 10000
gamma: 0.90  # discount factor
c: 500  # num steps after which to do target update
lr: 0.00025
checkpoint_every: 2
home_directory: /Users/pierclgr/PycharmProjects/AAS_project/
env_name: BreakoutNoFrameskip-v4
model: DQNNetwork
output_model_file: breakout_final_model
logging: false
num_testing_episodes: 2