preprocessing:
  n_frames_to_skip: 4
  n_frames_per_state: 4
  patch_size: 84
  grayscale: true
buffer_capacity: 10000
num_episodes: 500
batch_size: 32
eps_max: 1
eps_min: 0.01
eps_decay_steps: 1000000
gamma: 0.90  # discount factor
c: 500  # num steps after which to do target update
lr: 0.00025
checkpoint_every: 50
home_directory: /Users/pierclgr/PycharmProjects/AAS_project/
env_name: BreakoutNoFrameskip-v4
checkpoint_file: breakout_checkpoint
video_file: breakout
model: DQNNetwork
output_model_file: breakout_final_model
max_steps_per_episode: 10000
logging: true
in_colab: true
train_seed: 1507
test_seed: 1507