preprocessing:
  n_frames_to_skip: 4
  n_frames_per_state: 4
  patch_size: 84
  grayscale: true
  noop_max: 30
  scale_obs: true
  episode_life: true
  clip_rewards: true
  fire_reset: false
buffer_capacity: 100000 # 1000000
num_initial_replay_samples: 5000 # 50000
num_training_steps: 50000000
batch_size: 32
buffered_avg_reward_size: 100
num_parallel_envs: 13 # 32
eps_max: 1
eps_min: 0.1
eps_decay_steps: 1000000
gamma: 0.99  # discount factor
c: 10000  # num steps after which to do target update
checkpoint_every_n_gradient_steps: 100 # 2000
test_every_n_gradient_steps: 100
home_directory: /Users/pierclgr/PycharmProjects/AAS_project/
env_name: BreakoutNoFrameskip-v4
wandb_run_name: Train_Breakout_DQN
checkpoint_file: breakout_dqn_checkpoint
agent: DoubleDQNAgent
model: DQNNetwork
output_model_file: breakout_final_model
max_steps_per_episode: 1000
logging: false # true
save_space: true
test_video:
  file_name: train_breakout
  save_every_n_gradient_steps: 100 # 2000
  output_folder: test_videos/
reproducibility:
  train_seed: 1507
  test_seed: 2307
optimizer:
  lr: 0.00025
  momentum: 0.95
  squared_momentum: 0.95
  min_squared_gradient: 0.01